name: Run Unit Testing On Pull Request

on:
  pull_request:
    branches-ignore:
      - "*"
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  base-setup:
    name: Setting up Base system
    runs-on: ubuntu-latest
    outputs:
      node-path: ${{ steps.node.outputs.node-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

  unit-test-ui:
    name: Unit Test UI Package
    runs-on: ubuntu-latest
    needs: base-setup
    steps:
      - name: Install dependencies   
        run: pnpm install

      - name: Start UI Unit Testing
        run: pnpm test --filter ui
# rest of unit testings
