import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/ui/styles/globals.css";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { MainWrapper } from "@/components/mainwrapper";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ThemeProvider attribute={"class"} defaultTheme="dark">
          <MainWrapper>{children}</MainWrapper>
        </ThemeProvider>

        <Toaster position="bottom-center" richColors={true} theme="dark" />

        <script
          async
          src="https://cse.google.com/cse.js?cx=c425ced687cdd4142"
        ></script>
        <div className="gcse-search"></div>
      </body>
    </html>
  );
}
